# Generated by Django 5.1.3 on 2024-11-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('business', 'Anbieter'), ('customer', 'Kunde')], max_length=50, verbose_name='Profiltyp'),
        ),
    ]
