# Generated by Django 5.1.3 on 2024-11-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repeated_password',
        ),
    ]
