# Generated by Django 5.1.3 on 2024-11-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_customuser_description_customuser_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='file',
        ),
    ]
