# Generated by Django 5.1.3 on 2024-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_remove_user_repeated_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('customer', 'customer')], max_length=50, verbose_name='Profiltyp'),
        ),
    ]
